### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by tringler** [TheBestMoshe/home-assistant-addons#11]
Hello,

@TheBestMoshe do you still maintain that repo? I don't see activity since February. It is just a question. I don't want to push you or anything else.

Thanks, Thomas

**Comment by tringler** [comment]
Hello @TheBestMoshe,

I really would like to see paperless 1.4.4 in the repo, because of new important features like color-picker in the tag create dialog. Just let me know if I should fork the repo and implement the change, because there is already an open PR to update to v1.2.0. I would also post that to the HomeAssistant forum in the known thread, but I think its a bad style to do that without your agreement.

**Comment by TheBestMoshe** [comment]
@tringler Sorry about the delay. I missed your last message.

I don't have time right now to update it. However, if you can make a PR with the updates I would greatly appreciate it.

**Comment by lociii** [comment]
Submitted PR #14 to update to paperless-ng 1.5.0

**Comment by TheBestMoshe** [comment]
> Submitted PR #14 to update to paperless-ng 1.5.0

Thanks so much!

**Comment by ghost** [comment]
Any ETA when you will bump to the latest version 1.7.1?
