### ISSUE TITLE
Docker image not published

### ISSUE THREAD

**Issue by lociii** [TheBestMoshe/home-assistant-addons#15]
AFAIU the publish action is not run as there is no release tagged.

> Can't install cyclickdevelopment/paperless-ng-addon-amd64:1.5.0-0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=1.5.0-0&fromImage=cyclickdevelopment%2Fpaperless-ng-addon-amd64: Not Found ("manifest for cyclickdevelopment/paperless-ng-addon-amd64:1.5.0-0 not found: manifest unknown: manifest unknown")

Latest release on docker hub is 0.2.2, see https://hub.docker.com/r/cyclickdevelopment/paperless-ng-addon-amd64/tags

**Comment by tomvanswam** [comment]
I'm getting the same error when trying to upgrade

**Comment by overkill2010** [comment]
I'm getting the same error when trying to upgrade

**Comment by TheBestMoshe** [comment]
I just published it now. The Docker images should be available soon.

**Comment by lociii** [comment]
Image is available now and update went smoothly. Thanks!
