### ISSUE TITLE
paperless-ngx 1.6.0

### ISSUE THREAD

**Issue by tux2000** [TheBestMoshe/home-assistant-addons#17]
The development on the paperless-ng repo has stalled and thus new development is done in a forked version on https://github.com/paperless-ngx/paperless-ngx

Would be amazing if your home assistant plugin would also support paperless-ngx

**Comment by Nils3311** [comment]
This would be great 😊!

**Comment by TheBestMoshe** [comment]
I plan on moving this repo to Paperless-ngx. I am going to try to get to it in the near future. 

It would be great if someone can open a PR with the necessary changes.

**Comment by axyjo** [comment]
Just put up a pull request to upgrade

**Comment by tux2000** [comment]
Now there is already paperless ngx 1.7.0 https://github.com/paperless-ngx/paperless-ngx/releases/tag/ngx-1.7.0

would be amazing to get this into home assistant 🙂
