### ISSUE TITLE
'CSRF verification failed' behind reverse proxy

### ISSUE THREAD

**Issue by ghost** [TheBestMoshe/home-assistant-addons#22]
After updating to v.1.7.0 I tried to access paperless from outside through Nginx Proxy Manager.

The login page does load, so the reverse proxy seems to work fine.

But after logging in, I only get this 'CSRF verification failed' error message:

https://github.com/paperless-ngx/paperless-ngx/issues/712

The URL is set up correctly in form of:

`url: https://paperless.mydomain.com`

Any ideas? I did already restart HA and the whole machine.

I'm not sure if paperless-ngx does really receive the correct URL setting.

**Comment by tobi1449** [comment]
Same issue here. 
Probably the parsing of the url from the options.json fails. 

From my logfile:

```
jq: error: syntax error, unexpected INVALID_CHARACTER (Unix shell quoting issues?) at <top-level>, line 1:
.url // ''        
jq: 1 compile error
```
