### ISSUE TITLE
Add GitHub Action to build container images

### ISSUE THREAD

**Issue by TheBestMoshe** [TheBestMoshe/home-assistant-addons#4]
Whenever the addon changes version numbers, we should automatically build the Docker containers for each platform using GitHub Actions

**Comment by petewasher** [comment]
I started to take a look at this, which you can see [here](https://github.com/petewasher/home-assistant-addons/pull/1) on my fork. Builds surprisingly quickly vs my laptop :laughing:

Do you have a docker-hub repository you want to use for this? For the `publish` action which actually pushes to dockerhub, you would need to setup secrets in the repo for `username` and `token`. See [this example](https://github.com/home-assistant/builder#publish-action-example), and the steps for [setting up the secrets](https://docs.github.com/en/actions/reference/encrypted-secrets).

**Comment by TheBestMoshe** [comment]
I added the username and token to the repo

**Comment by petewasher** [comment]
Created #6 to cover this issue.
