### ISSUE TITLE
Upgrade to Paperless-ng version 1.2.0

### ISSUE THREAD

**Issue by TheBestMoshe** [TheBestMoshe/home-assistant-addons#7]
[Changelog](https://paperless-ng.readthedocs.io/en/latest/changelog.html#paperless-ng-1-2-0)

Note: Paperless no longer depends on `libpoppler-cpp-dev`. This can now be removed from the Dockerfile.

**Comment by lociii** [comment]
Now at release 1.4.0

**Comment by lociii** [comment]
Submitted PR #14 to upgrade to paperless-ng 1.5.0

**Comment by TheBestMoshe** [comment]
Closed by #14
